# CRIANDO TO DO LIST DO ZERO
# 1: LISTA COM COMANDOS BÁSICOS (ADICIONAR, EXCLUIR, CONCLUIR, LIMPAR TUDO, MOSTRAR TAREFAS.)

print("TO DO LIST")
print("O QUE DESEJA FAZER?\n1: ADICIONAR TAREFA.\n2: REMOVER TAREFA.\n3: CONCLUIR TAREFA.\n4: LIMPAR TUDO.\n5: MOSTRAR TAREFAS.")
